export const NewsList = [
  {
    title: "OpenFHE (Fully Homomorphic Encryption)",
    link: "https://www.openfhe.org/",
    comments: 4,
    time: "58 minutes ago",
    points: "2",
    author: "John davis",
  },
  {
    title: "Quadratic Sieve – Factoring Fast",
    link: "https://www.youtube.com/watch?v=x5LTBsmGfFc",
    comments: 2,
    time: "1 hour ago",
    points: "0",
    author: "davis",
  },
  {
    title: "NFT royalties on secondary market arent mandatory",
    link: "https://www.openfhe.org/",
    comments: 0,
    time: "1 hour ago",
    points: "5",
    author: "pablo",
  },
  {
    title: "OpenFHE (Fully Homomorphic Encryption)",
    link: "https://www.openfhe.org/",
    comments: 0,
    time: "4 hour ago",
    points: "0",
    author: "catos",
  },
  {
    title: "US hospitals are so overloaded that one ER called 911 on itself",
    link: "https://arstechnica.com/science/2022/11/us-hospitals-are-so-overloaded-that-one-er-called-911-on-itself/",
    comments: 2,
    time: "6 hour ago",
    points: "5",
    author: "dr hollivr",
  },
  {
    title: "US hospitals are overloaded that one ER called ",
    link: "https://arstechnica.com/science/2022/11/us-hospitals-are-so-overloaded-that-one-er-called-911-on-itself/",
    comments: 2,
    time: "6 hour ago",
    points: "5",
    author: "dr hollivr",
  },
  {
    title: "US hospitals are so overloaded led  on itself",
    link: "https://arstechnica.com/science/2022/11/us-hospitals-are-so-overloaded-that-one-er-called-911-on-itself/",
    comments: 2,
    time: "6 hour ago",
    points: "5",
    author: "dr hollivr",
  },
  {
    title: " hospitals are so overloaded that one ER called 911 on itself",
    link: "https://arstechnica.com/science/2022/11/us-hospitals-are-so-overloaded-that-one-er-called-911-on-itself/",
    comments: 2,
    time: "6 hour ago",
    points: "5",
    author: "dr hollivr",
  },
  {
    title: "Nimpressions",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 7,
    time: "8 hour ago",
    points: "2",
    author: "pillaor",
  },
  {
    title: "Using Wi-FI to See Through Walls",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 7,
    time: "12 hour ago",
    points: "1",
    author: "pillaor",
  },
  {
    title: "A Reader Mode Proxy for the Slow Web Written in Rust",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 0,
    time: "1 day ago",
    points: "0",
    author: "ross geller",
  },
  {
    title: "UK grocery price inflation hits record 14.7%",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 1,
    time: "1 day ago",
    points: "5",
    author: " geller",
  },
  {
    title:
    "FTX Appears to Have Stopped Processing Withdrawals, On-Chain Data Show",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 2,
    time: "1 day ago",
    points: "0",
    author: "kratosss",
  },
  {
    title: "Scaling PostgresML to 1M Requests per Second",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 67,
    time: "1 day ago",
    points: "0",
    author: "ross geller",
  },
  {
    title: "Being a Solo Software Entrepreneur at 40",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 24,
    time: "1 day ago",
    points: "3",
    author: "geo",
  },
  {
    title: " Solo Software Entrepreneur 0",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 0,
    time: "1 day ago",
    points: "3",
    author: "geos",
  },
  {
    title: "Mail: Make The Dragonfly Mail Agent (dma) the default mta",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 7,
    time: "1 day ago",
    points: "0",
    author: "nasor",
  },
  {
    title: "Maps and Memory Leaks in Go",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 9,
    time: "2 day ago",
    points: "9",
    author: "easy pee",
  },
  {
    title: "AI Data Laundering",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 1,
    time: "3 day ago",
    points: "7",
    author: " pee",
  },
  {
    title: "Dragonfly Mail Agent ",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 1,
    time: "3 day ago",
    points: "7",
    author: " pee",
  },
  {
    title: " inflation hits record 14.7%",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 6,
    time: "5 day ago",
    points: "5",
    author: " misss",
  },
  {
    title: "Intel plans thousands of job cuts in face of PC slowdown",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 4,
    time: "5 day ago",
    points: "90",
    author: " waysss",
  },

  {
    title:
    "ByteDance planned to use TikTok to surveil specific American citizens",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 2,
    time: "1 day ago",
    points: "9",
    author: " kattils",
  },
  {
    title: "Factorio for Nintendo Switch is now available",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 8,
    time: "8 day ago",
    points: "9",
    author: " kattils",
  },
  {
    title: " Nintendo Switch is now available",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 8,
    time: "8 day ago",
    points: "12",
    author: " kattils",
  },
  {
    title: "Apple is quietly pushing a TV ad product with media agencies",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 1,
    time: "8 day ago",
    points: "12",
    author: " kattils",
  },
  {
    title: "Ask HN: What are some of the best books you have read in 2022?",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 8,
    time: "8 day ago",
    points: "12",
    author: " kattils",
  },
  {
    title: "Zig Is Self-Hosted Now, Whats Next?",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 0,
    time: "10 day ago",
    points: "5",
    author: " kanjuss",
  },
  {
    title: "NYC to require salary ranges be included in job postings",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 3,
    time: "12 day ago",
    points: "12",
    author: " priya",
  },
  {
    title: "Intel plans thousands of job cuts in face of PC slowdown",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 6,
    time: "14 day ago",
    points: "12",
    author: " meera",
  },
  {
    title: "Disposable Root Servers",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 8,
    time: "15 day ago",
    points: "12",
    author: " kattils",
  },
  {
    title: "How to prove you know a secret without giving it away",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 0,
    time: "15 day ago",
    points: "5",
    author: " kanjuss",
  },
  {
    title: "San Francisco to Spend $1.7M to Build a Single Public Toilet",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 3,
    time: "15 day ago",
    points: "12",
    author: " priya",
  },
  {
    title: "Negative 2000 Lines of Code (1982)",
    link: "https://blog.hyperlinkyourheart.com/",
    comments: 6,
    time: "15 day ago",
    points: "12",
    author: " meera",
  },

];
